// Autogenerated from Pigeon (v10.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class ScannedBarcodesResponse {
  ScannedBarcodesResponse({
    required this.barcodes,
  });

  List<ScannedBarcode?> barcodes;

  Object encode() {
    return <Object?>[
      barcodes,
    ];
  }

  static ScannedBarcodesResponse decode(Object result) {
    result as List<Object?>;
    return ScannedBarcodesResponse(
      barcodes: (result[0] as List<Object?>?)!.cast<ScannedBarcode?>(),
    );
  }
}

class ScannedBarcode {
  ScannedBarcode({
    required this.barcode,
    this.boundLeft,
    this.boundTop,
    this.boundRight,
    this.boundBottom,
  });

  String barcode;

  int? boundLeft;

  int? boundTop;

  int? boundRight;

  int? boundBottom;

  Object encode() {
    return <Object?>[
      barcode,
      boundLeft,
      boundTop,
      boundRight,
      boundBottom,
    ];
  }

  static ScannedBarcode decode(Object result) {
    result as List<Object?>;
    return ScannedBarcode(
      barcode: result[0]! as String,
      boundLeft: result[1] as int?,
      boundTop: result[2] as int?,
      boundRight: result[3] as int?,
      boundBottom: result[4] as int?,
    );
  }
}

class _QrMobileVisionApiCodec extends StandardMessageCodec {
  const _QrMobileVisionApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is ScannedBarcode) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is ScannedBarcodesResponse) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return ScannedBarcode.decode(readValue(buffer)!);
      case 129: 
        return ScannedBarcodesResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class QrMobileVisionApi {
  static const MessageCodec<Object?> codec = _QrMobileVisionApiCodec();

  void onScannedBarcode(ScannedBarcodesResponse barcode);

  static void setup(QrMobileVisionApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.qr_mobile_vision.QrMobileVisionApi.onScannedBarcode', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.qr_mobile_vision.QrMobileVisionApi.onScannedBarcode was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ScannedBarcodesResponse? arg_barcode = (args[0] as ScannedBarcodesResponse?);
          assert(arg_barcode != null,
              'Argument for dev.flutter.pigeon.qr_mobile_vision.QrMobileVisionApi.onScannedBarcode was null, expected non-null ScannedBarcodesResponse.');
          api.onScannedBarcode(arg_barcode!);
          return;
        });
      }
    }
  }
}
